# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/notes_stable_diffusion',
                'doc_host': 'https://pankaj-kvhld.github.io',
                'git_url': 'https://github.com/pankaj-kvhld/notes_stable_diffusion',
                'lib_path': 'notes_stable_diffusion'},
  'syms': {'notes_stable_diffusion.core': {'notes_stable_diffusion.core.foo': ('core.html#foo', 'notes_stable_diffusion/core.py')}}}
